from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from core.result import TaskResult
from tasks.task_registry import create_task


def print_result(result: TaskResult) -> None:
    print(result.message)
    print(f"status: {result.status}")
    if result.audit_status:
        print(f"audit_status: {result.audit_status}")
    if result.run_id:
        print(f"run_id: {result.run_id}")
    if result.report_path:
        print(f"report_path: {result.report_path}")
    for warning in result.warnings:
        print(f"WARNING: {warning}")
    if result.status == "INVALID" and result.warnings:
        print("INVALID 原因：")
        for warning in result.warnings:
            print(f"- {warning}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="AI_AStock_Quant_System CLI")
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("generate-sample-data")
    p.add_argument("--timeframe", default="1d")
    p.add_argument("--symbol", default="601088.SH")
    sub.add_parser("course-demo")
    p = sub.add_parser("core5-walk-forward")
    p.add_argument("--out", default="reports/core5_relative_strength_grid_package")
    p.add_argument("--starts", default="2018,2019,2020,2021")
    p.add_argument("--n-random", dest="n_random", type=int, default=297)
    p = sub.add_parser("core5-live-signal")
    p.add_argument("--data-dir", default="/Users/shejishi/Desktop/30分钟股票数据")
    p.add_argument("--as-of")
    p.add_argument("--current-symbol")
    p.add_argument("--current-shares", type=int)
    p.add_argument("--cash", type=float)
    p.add_argument("--equity", type=float)
    p.add_argument("--current-drawdown", type=float)
    p.add_argument("--start-date", default="2017-01-01")
    p.add_argument("--end-date", default="2026-06-26")
    p.add_argument("--allow-historical", action="store_true")
    p = sub.add_parser("core5-signal-sandbox")
    p.add_argument("--signal", required=True)
    p.add_argument("--config", default="config/qmt_config.yaml")
    p.add_argument("--confirmation", default="")
    for name in ["backtest", "optimize", "paper"]:
        p = sub.add_parser(name)
        p.add_argument("--strategy", required=True)
        p.add_argument("--symbol", required=True)
        p.add_argument("--data", default="__auto_fetch__")
        p.add_argument("--timeframe", default="1d")
        p.add_argument("--adjust", default="raw")
        p.add_argument("--strategy-params", default="{}")
        if name == "paper":
            p.add_argument("--plan-run-id")
    p = sub.add_parser("audit")
    p.add_argument("--run-id", required=True)
    p = sub.add_parser("qmt-config-init")
    p.add_argument("--config", default="config/qmt_config.yaml")
    p.add_argument("--account-id")
    p.add_argument("--mini-qmt-path")
    p.add_argument("--session-id", type=int)
    p.add_argument("--force", action="store_true")
    p = sub.add_parser("qmt-config-status")
    p.add_argument("--config", default="config/qmt_config.yaml")
    sub.add_parser("qmt-check")
    p = sub.add_parser("pretrade-check")
    p.add_argument("--strategy", required=True)
    p.add_argument("--symbol", required=True)
    p.add_argument("--confirmation", default="")
    p.add_argument("--run-id", default="latest")
    p.add_argument("--plan-run-id")
    p.add_argument("--qmt-run-id")
    p = sub.add_parser("pretrade-package")
    p.add_argument("--promotion", required=True)
    p.add_argument("--symbol")
    p.add_argument("--strategy", default="compiled_repair_dsl")
    p.add_argument("--qmt-run-id")
    p.add_argument("--confirmation", default="")
    p = sub.add_parser("pretrade-runbook-refresh")
    p.add_argument("--package", required=True)
    p.add_argument("--symbol")
    p.add_argument("--strategy")
    p.add_argument("--qmt-run-id")
    p.add_argument("--confirmation", default="")
    p = sub.add_parser("qmt-handoff")
    p.add_argument("--package", required=True)
    p.add_argument("--action", required=True)
    p.add_argument("--quantity", required=True, type=int)
    p.add_argument("--price", type=float)
    p.add_argument("--symbol")
    p.add_argument("--signal-time", required=True)
    p.add_argument("--execute-time", required=True)
    p.add_argument("--timeframe", default="1d")
    p.add_argument("--reason", default="")
    p = sub.add_parser("qmt-handoff-wizard")
    p.add_argument("--package", required=True)
    p.add_argument("--action", required=True)
    p.add_argument("--quantity", required=True, type=int)
    p.add_argument("--price", type=float)
    p.add_argument("--symbol")
    p.add_argument("--signal-time", required=True)
    p.add_argument("--execute-time", required=True)
    p.add_argument("--timeframe", default="1d")
    p.add_argument("--reason", default="")
    p.add_argument("--qmt-run-id")
    p.add_argument("--trade-date")
    p.add_argument("--config", default="config/qmt_config.yaml")
    p.add_argument("--notes", default="")
    p = sub.add_parser("qmt-batch-handoff")
    p.add_argument("--package", required=True)
    p.add_argument("--orders", required=True)
    p.add_argument("--default-timeframe", default="1d")
    p = sub.add_parser("qmt-batch-handoff-wizard")
    p.add_argument("--package", required=True)
    p.add_argument("--orders", required=True)
    p.add_argument("--default-timeframe", default="1d")
    p.add_argument("--qmt-run-id")
    p.add_argument("--trade-date")
    p.add_argument("--config", default="config/qmt_config.yaml")
    p.add_argument("--notes", default="")
    p = sub.add_parser("qmt-batch-sandbox")
    p.add_argument("--batch-handoff", required=True)
    p.add_argument("--config", default="config/qmt_config.yaml")
    p.add_argument("--confirmation", default="")
    p = sub.add_parser("qmt-batch-lifecycle")
    p.add_argument("--batch-sandbox", required=True)
    p.add_argument("--qmt-run-id")
    p = sub.add_parser("qmt-batch-daily-review")
    p.add_argument("--batch-lifecycle", required=True)
    p.add_argument("--trade-date")
    p.add_argument("--notes", default="")
    p = sub.add_parser("qmt-order-sandbox")
    p.add_argument("--handoff", required=True)
    p.add_argument("--config", default="config/qmt_config.yaml")
    p.add_argument("--confirmation", default="")
    p = sub.add_parser("qmt-order-lifecycle")
    p.add_argument("--sandbox", required=True)
    p.add_argument("--qmt-run-id")
    p = sub.add_parser("qmt-daily-review")
    p.add_argument("--lifecycle", required=True)
    p.add_argument("--trade-date")
    p.add_argument("--notes", default="")
    p = sub.add_parser("qmt-readiness-dashboard")
    p.add_argument("--pretrade-package")
    p.add_argument("--runbook-refresh")
    p.add_argument("--handoff-wizard")
    p.add_argument("--batch-handoff-wizard")
    p.add_argument("--daily-review")
    p.add_argument("--batch-daily-review")
    p = sub.add_parser("stage-check")
    p.add_argument("--run-id", default="latest")
    p.add_argument("--plan-run-id")
    p.add_argument("--qmt-run-id")
    p = sub.add_parser("student-workflow")
    p.add_argument("--idea", required=True)
    p.add_argument("--symbol")
    p.add_argument("--strategy")
    p.add_argument("--strategy-params", default="{}")
    p.add_argument("--data", default="__auto_fetch__")
    p.add_argument("--timeframe", default="1d")
    p.add_argument("--adjust", default="point_in_time_qfq")
    p.add_argument("--include-qmt", action="store_true")
    p.add_argument("--auto-refine", action="store_true")
    p.add_argument("--max-refinements", type=int, default=1)
    p.add_argument("--session-id")
    p.add_argument("--case-id")
    p = sub.add_parser("student-backtest-plan-precheck")
    p.add_argument("--idea")
    p.add_argument("--timeframe")
    p.add_argument("--adjust", default="point_in_time_qfq")
    p.add_argument("--strategy-pattern")
    p.add_argument("--session-id")
    p.add_argument("--case-id")
    p = sub.add_parser("student-course-path")
    p.add_argument("--idea")
    p.add_argument("--timeframe")
    p.add_argument("--adjust", default="point_in_time_qfq")
    p.add_argument("--strategy-pattern")
    p.add_argument("--file")
    p.add_argument("--code")
    p.add_argument("--session-id")
    p.add_argument("--case-id")
    p = sub.add_parser("student-contract-check")
    p.add_argument("--contract")
    p.add_argument("--workflow")
    p.add_argument("--session-id")
    sub.add_parser("student-doctor")
    p = sub.add_parser("student-future-leak-precheck")
    p.add_argument("--file")
    p.add_argument("--code")
    p.add_argument("--strategy-name")
    p.add_argument("--session-id")
    p = sub.add_parser("student-first-run")
    p.add_argument("--idea", required=True)
    p.add_argument("--timeframe")
    p.add_argument("--adjust", default="point_in_time_qfq")
    p.add_argument("--session-id")
    p.add_argument("--case-id")
    p.add_argument("--execute", action="store_true")
    p.add_argument("--timeout-seconds", type=int, default=300)
    p = sub.add_parser("student-handoff-pack")
    p.add_argument("--workflow")
    p.add_argument("--session-id")
    p.add_argument("--no-product-audit", action="store_true")
    p.add_argument("--no-session-report", action="store_true")
    p = sub.add_parser("student-idea-preflight")
    p.add_argument("--idea")
    p.add_argument("--timeframe")
    p.add_argument("--adjust", default="point_in_time_qfq")
    p.add_argument("--session-id")
    p.add_argument("--case-id")
    p.add_argument("--no-auto-refine", action="store_true")
    p = sub.add_parser("student-control-center")
    p.add_argument("--workflow")
    p.add_argument("--promotion")
    p.add_argument("--qmt-dashboard")
    p.add_argument("--session-id")
    p = sub.add_parser("student-run-next")
    p.add_argument("--workflow")
    p.add_argument("--promotion")
    p.add_argument("--qmt-dashboard")
    p.add_argument("--session-id")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--timeout-seconds", type=int, default=180)
    p = sub.add_parser("student-product-audit")
    p.add_argument("--workflow")
    p.add_argument("--limit", type=int, default=5)
    p = sub.add_parser("student-research-contract")
    p.add_argument("--idea")
    p.add_argument("--timeframe")
    p.add_argument("--adjust", default="point_in_time_qfq")
    p.add_argument("--strategy-pattern")
    p.add_argument("--file")
    p.add_argument("--code")
    p.add_argument("--session-id")
    p.add_argument("--case-id")
    p = sub.add_parser("student-start")
    p.add_argument("--workflow")
    p.add_argument("--promotion")
    p.add_argument("--qmt-dashboard")
    p.add_argument("--session-id")
    p.add_argument("--no-session-index", action="store_true")
    p.add_argument("--no-preview", action="store_true")
    p = sub.add_parser("student-safe-loop")
    p.add_argument("--workflow")
    p.add_argument("--promotion")
    p.add_argument("--qmt-dashboard")
    p.add_argument("--session-id")
    p.add_argument("--max-steps", type=int, default=3)
    p.add_argument("--execute", action="store_true")
    p.add_argument("--timeout-seconds", type=int, default=180)
    p = sub.add_parser("student-session-index")
    p.add_argument("--limit", type=int, default=50)
    p = sub.add_parser("student-session-report")
    p.add_argument("--ledger", default="reports/student_session_ledger.jsonl")
    p.add_argument("--limit", type=int, default=20)
    p.add_argument("--session-id")
    p = sub.add_parser("repair-dsl-backtest")
    p.add_argument("--dsl", required=True)
    p.add_argument("--symbol")
    p.add_argument("--data", default="__auto_fetch__")
    p.add_argument("--timeframe")
    p.add_argument("--adjust")
    p.add_argument("--paper-observation", action="store_true")
    p.add_argument("--stage-check", action="store_true")
    p.add_argument("--qmt-run-id")
    p.add_argument("--auto-repair", action="store_true")
    p = sub.add_parser("research")
    p.add_argument("--direction", required=True)
    p.add_argument("--symbol", required=True)
    p.add_argument("--data", default="__auto_fetch__")
    p.add_argument("--timeframe", default="1d")
    p.add_argument("--adjust", default="raw")
    p = sub.add_parser("optimize-loop")
    p.add_argument("--idea", required=True)
    p.add_argument("--symbol", required=True)
    p.add_argument("--timeframe", default="1d")
    p.add_argument("--adjust", default="raw")
    p.add_argument("--max-iterations", dest="max_iterations", type=int, default=8)
    sub.add_parser("doctor")
    p = sub.add_parser("explain-report")
    p.add_argument("--run-id", required=True)
    p = sub.add_parser("build-adjustment-factors")
    p.add_argument("--symbol", required=True)
    p.add_argument("--corporate-actions", required=True)
    p = sub.add_parser("intake")
    p.add_argument("--idea")
    p.add_argument("--interactive", action="store_true")
    p = sub.add_parser("intake-chat")
    p.add_argument("--idea")
    p.add_argument("--confirm", action="store_true")
    for name in ["fetch-data", "update-data", "data-status"]:
        p = sub.add_parser(name)
        p.add_argument("--symbol", required=True)
        p.add_argument("--timeframe", default="1d")
        p.add_argument("--adjust", default="raw")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    task = create_task(args.command)
    result = task.run(**vars(args))
    print_result(result)
    return 0 if result.status in {"VALID", "INVALID"} else 1


if __name__ == "__main__":
    raise SystemExit(main())
